### ISSUE TITLE
can't put file to dhfs

### ISSUE THREAD

**Issue by wsxzhmzwdfxeds** [wsxzhmzwdfxeds/kube-hdfs#1]
I have built HDFS on kubernetes, when i put files, some execption happend:
           Exception in createBlockOutputStream
org.apache.hadoop.net.ConnectTimeoutException: 60000 millis timeout while waiting for channel to be ready for connect. ch : java.nio.channels.SocketChannel[connection-pending remote=/172.16.85.0:50010]
Put file could only be replicated to 0 nodes instead of minReplication (=1).  There are 2 datanode(s) running and 2 node(s) are excluded in this operation.

**Comment by wsxzhmzwdfxeds** [comment]
@lvlv   can you teach me how to deploy this.

**Comment by lvlv** [comment]
The client has to join flannel network, otherwise it can't connect to datanode directly.
You may ping your datanode from your client machine to test this.

**Comment by wsxzhmzwdfxeds** [comment]
@lvlv  each node can ping others successfully,  but when I use hdfsadmin -report on namenode,
the ip of slave node is : Name: 172.16.85.0:50010 (172.16.85.0)
                                      Hostname: slave2
datanode ip is 172.16.85.2 .  so I think namenode can only find 172.16.85.0  , and when I create file,
Excluding datanode 172.16.85.0:50010 ,DataStreamer Exception happends.

**Comment by lvlv** [comment]
That's the issue, you may find out why slave2 is resolved to 172.16.85.0, can you ping slave2 from namenode? Does 172.16.85.0 belong to any host?

**Comment by wsxzhmzwdfxeds** [comment]
@lvlv  172.16.85.0 is flannel.1  . docker0 ip is 172.16.85.1 
namenode can ping slave2.  and  namenode can ping docker0 .but cannot ping flannel.1

the state of flannel.1 is UNKNOWN, does this matter?
 flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
    link/ether d2:91:9c:04:d4:02 brd ff:ff:ff:ff:ff:ff
    inet 172.16.30.0/16 scope global flannel.1

**Comment by lvlv** [comment]
may I see your hdfs-site.xml and namenode service definition?

**Comment by wsxzhmzwdfxeds** [comment]
@lvlv   I put core-site.xml and hdfs-site.xml at  https://github.com/yangshuai93/kube-hdfs/tree/yangshuai93-patch-1
do you need anything more?

**Comment by lvlv** [comment]
see https://github.com/kubernetes/kubernetes/issues/26546
The master service must be headless (http://kubernetes.io/docs/user-guide/services/#headless-services)

**Comment by wsxzhmzwdfxeds** [comment]
@lvlv    I have put all the files at  https://github.com/yangshuai93/kube-hdfs/tree/yangshuai93-patch-1 the master service and slave1 service all use the headless service   like this ?

**Comment by wsxzhmzwdfxeds** [comment]
@lvlv  this problem still exsit...
when i use " hdfs dfsadmin -report "  
Live datanodes:
 Name: 172.16.68.0:50010 (172.16.68.0)

**Comment by wsxzhmzwdfxeds** [comment]
1. tell docker not to install the masquerading rule. in docker 1.3+, do --ip-masq=false when starting the docker daemon
2. tell flannel to install the masquerading rule that is "wider": starting flannel with --ip-masq=true

**Comment by lvlv** [comment]
Great you dig out :+1:

**Comment by wsxzhmzwdfxeds** [comment]
@lvlv  thank you  ! you are  yi ge hao ren !
